### Modules

In [287]:
import numpy as np
from sklearn.linear_model import LinearRegression 
import matplotlib.pyplot as plt

### Data

In [288]:
price = [0.52812, 0.52898, 0.53394, 0.52807, 0.52757, 0.53320, 0.52954, 0.53303, 0.52216, 0.52548, 0.52379, 0.52000, 0.53191, 0.53732, 0.53687, 0.53495, 0.53495, 0.53602, 0.53455, 0.53337]

In [289]:
Y = np.array(price)

In [290]:
X = np.array([np.arange(0,len(Y))]).T

In [291]:
print(len(X), len(Y))

20 20


### Apply Linear Regression model of SciKitLearn

In [292]:
regression = LinearRegression()

In [293]:
regression.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

### Model

In [294]:
regression.intercept_

0.52733399999999997

In [295]:
regression.coef_

array([ 0.00035337])

In [296]:
regression.score(X, Y)

0.17227689412293767

##### So, Y = intercept_ + [(coef_)(X)]  and Adj. R-squared = score 

### Prediction for:

In [297]:
regression.predict(20)

array([ 0.53440137])

### Statistics

In [298]:
Y_predicted = regression.predict(X)

In [299]:
SSD = np.sum((Y_predicted - Y) ** 2) 
SSD

0.00039896533473684316

Standard Desviation

In [300]:
RSE = np.sqrt(SSD / len(X))
RSE

0.0044663482552127704

In [301]:
price_mean = np.mean(Y)
price_mean

0.53069100000000002

In [302]:
error = RSE / price_mean
error

0.0084160994914418558

#### Prediction at 8:00 pm

In [303]:
at_8 = regression.predict(20)

In [304]:
at_8 - RSE, at_8, at_8 + RSE

(array([ 0.52993502]), array([ 0.53440137]), array([ 0.53886772]))

* This was computed 1 hour before

## Real price = 0.53224